# Generated by Django 5.1.6 on 2025-05-01 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_subcategories_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='parent',
        ),
    ]
