# Generated by Django 5.1.6 on 2025-05-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='path',
            field=models.CharField(default=(1, 2, 3), max_length=120),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductsSubcategoriesChildParentRelation',
        ),
    ]
